name: Generate Snake

on:
  # 每天午夜自动运行
  schedule:
    - cron: "0 0 * * *" 
  
  # 允许手动触发
  workflow_dispatch:

  # 为了方便调试，当推送到 main 分支时也自动运行
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # 使用 v3 版本的 Action
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            # color_snake: 设为最亮的荧光青 (#00ffb1)
            # color_dots: 背景(#000000) -> 深紫(#2f006f) -> 紫(#5e00ff) -> 粉紫(#e500ff) -> 荧光青(#00ffb1)
            dist/github-contribution-grid-snake.svg?color_snake=#00ffb1&color_dots=#000000,#2f006f,#5e00ff,#e500ff,#00ffb1
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00ffb1&color_dots=#000000,#2f006f,#5e00ff,#e500ff,#00ffb1
      # 将生成的文件推送到 output 分支
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
